### ISSUE TITLE
tag display error

### ISSUE THREAD

**Issue by Nhiet-MD** [colineckert/obsidian-things#84]
Hello. I've just updated the theme inside Obsidian, and now my tags look like this. It still remain when zooming in/out, and even after restarting Obsidian.

Please have a look at this. Thank you very much!

![image](https://user-images.githubusercontent.com/112700361/188129334-746468b6-23a4-4ef3-b0ac-1fca6fb311ef.png)

**Comment by Hbbb** [comment]
Version Information:
```
Version 0.15.9 (installer 0.15.9)
```
I'm also seeing this. Tags look like this to me.
![SCR-20220918-pu8](https://user-images.githubusercontent.com/3803272/190930748-d9b1a778-adab-41aa-99fe-1f2f82cdcdab.png)

**Comment by pavol6999** [comment]
For the sake of my sanity and OCD please we need a fix

**Comment by colineckert** [comment]
OK, I just pushed up a possible fix. Can someone on this thread update their theme and check if resolved? 

It's working on my end, but I've recently updgraded to the insider build to start working on v2 of the theme for the new Obsidian UI, so I'm not 100% sure it solves the issue.

Appreciate the help!

**Comment by universvm** [comment]
![Screenshot 2022-09-20 at 15 42 22](https://user-images.githubusercontent.com/17524568/191288600-6a2a528f-8d31-43e1-84d8-b9a51e679d9b.png)
Unfortunately I still have this. I am on version 15.9 @colineckert

**Comment by Nhiet-MD** [comment]
> OK, I just pushed up a possible fix. Can someone on this thread update their theme and check if resolved?
> 
> It's working on my end, but I've recently updgraded to the insider build to start working on v2 of the theme for the new Obsidian v0.16 UI, so I'm not 100% sure it solves the issue.
> 
> Appreciate the help!

Hello @colineckert , thank you for your new fix. I'm also on v15.9, and unfortunately, the problem still persist in my case in a "novel" way. As you can see, the tags's head parts now look a bit larger than the tail parts and remain that way as I zoom in and out.
![image](https://user-images.githubusercontent.com/112700361/191388641-481ef36c-542f-44c1-9bf2-a9740c4eff8d.png)
![image](https://user-images.githubusercontent.com/112700361/191388698-cc950750-3b15-46f0-95dd-b3f2618a7f47.png)
![image](https://user-images.githubusercontent.com/112700361/191388575-e6176aa8-09fe-46ff-b29b-bef87a14e2f3.png)

**Comment by vpark** [comment]
@Nhiet-MD I realize that this is off topic, but how did you generate your YAML content at the top? I'm curious as to how you created a date modified section that updates dynamically

**Comment by Nhiet-MD** [comment]
> 

I use a plugin called "Linter" by _Victor Tao_ to create such frontmatter, which updates itself when I press Ctrl/Cmd + S

**Comment by colineckert** [comment]
hey all, I just pushed another attempt at resolving this bug. It appears to be working for me locally, but can someone please confirm by updating their theme and checking? Thanks!!

**Comment by Selenuix** [comment]
> hey all, I just pushed another attempt at resolving this bug. It appears to be working for me locally, but can someone please confirm by updating their theme and checking? Thanks!!

Working as intended on my side, thank you! 😄

**Comment by marinoffDev** [comment]
> hey all, I just pushed another attempt at resolving this bug. It appears to be working for me locally, but can someone please confirm by updating their theme and checking? Thanks!!

That fixed it on my end as well 🎉Thank you so much!

**Comment by colineckert** [comment]
Great! Thanks for confirming @Selenuix and @marinoffDev! Closing this issue. I really appreciate everyone's patience and support! ❤️

**Comment by Selenuix** [comment]
You might consider reopening the issue. Not sure if it's fixed for others but basically:

- Works in preview mode (no change from https://github.com/colineckert/obsidian-things/issues/84#issuecomment-1258085756)
- Fixed in edition mode (https://github.com/colineckert/obsidian-things/commit/b217d852040d810fc08cde877f1b886e4a3def7c)
- **Not** fixed in source mode (see screenshot for more details)

![image](https://user-images.githubusercontent.com/29508475/192732980-d45adf10-dfdf-4f03-a0f3-8b6aaa3f1490.png)

Hope that helped 😄 If others could confirm, that'd be great.

**Comment by universvm** [comment]
Can confirm @Selenuix

**Comment by Nhiet-MD** [comment]
> hey all, I just pushed another attempt at resolving this bug. It appears to be working for me locally, but can someone please confirm by updating their theme and checking? Thanks!!

Everything's back to normal in my case. Thanks a lot!

**Comment by Selenuix** [comment]
> > hey all, I just pushed another attempt at resolving this bug. It appears to be working for me locally, but can someone please confirm by updating their theme and checking? Thanks!!
> 
> Everything's back to normal in my case. Thanks a lot!

Does it work in source mode as well?

**Comment by Nhiet-MD** [comment]
> > > hey all, I just pushed another attempt at resolving this bug. It appears to be working for me locally, but can someone please confirm by updating their theme and checking? Thanks!!
> > 
> > 
> > Everything's back to normal in my case. Thanks a lot!
> 
> Does it work in source mode as well?

I've been using Live Preview this whole time, now you mention it, the tag is indeed weird in Source Mode.
![image](https://user-images.githubusercontent.com/112700361/192771224-44023116-901e-498d-94c3-c221b58b12cd.png)

**Comment by colineckert** [comment]
Ah, I see, I was missing a selector for legacy source mode. Should be working now if someone can confirm. I'll reopen until the issue is confirmed resolved. Thanks!

**Comment by Selenuix** [comment]
![image](https://user-images.githubusercontent.com/29508475/192878958-50f347d0-92c1-47d7-b6f6-da2195cfb25b.png)

Just updated, but looks like it's still not working. Keep in mind that I'm on another PC right now and that I hadn't updated to post-fix version. Will try again on work laptop tomorrow and let you know.

@Nhiet-MD Update from your side?

**Comment by marinoffDev** [comment]
I typically don't use Source Mode, so I never noticed :/
Updated to the new version just now but the issue persists:
![image](https://user-images.githubusercontent.com/65615065/193031858-a36ebf0f-d116-484a-9258-d328e497e6bf.png)

**Comment by colineckert** [comment]
Hey everyone, have you upgraded to Obsidian 1.0 and Things v2 yet? This issue should no longer be occurring, but please let me know if you run into any bugs. Thanks!

**Comment by Selenuix** [comment]
> Hey everyone, have you upgraded to Obsidian 1.0 and Things v2 yet? This issue should no longer be occurring, but please let me know if you run into any bugs. Thanks!

Fixed on my side, even in source mode. Thank you 😄

**Comment by Selenuix** [comment]
This should probably be closed now, everything has been fixed.
